### ISSUE TITLE
Delete account 

### ISSUE THREAD

**Issue by fzerorubigd** [hazy-app/api#8]
I can not find any link to delete the account completely. Also disabling (in parallel with deleting, not as an alternative)  would be good.

**Comment by nainemom** [comment]
Yes you right. I'll keep this issue open until Delete Account is added to Hazy. Thanks.

**Comment by nainemom** [comment]
Actually a simple version of 'Delete Account' now added to API and you can call API to delete your account by yourself, but there is no plan yet to add it to GUI.
